[package]
authors = ["Vladas Zakrevksis <146100@gmail.com>"]
name = "rlpx-test"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
rlp = "0.5.2"
rand = "0.8.5"
parity-crypto = { version = "0.9.0", features = ["publickey"] }
