[package]
name = "rlpx-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlp = "0.5.2"
rand = "0.8.5"
parity-crypto = { version = "0.9.0", features = ["publickey"] }
