name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        target: [
          { runner: macos-latest },
          { runner: ubuntu-latest },
#          { runner: windows-latest },
        ]
    runs-on: ${{ matrix.target.runner }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build
        run: make

      - name: Build geth
        run: make geth

      - name: Test
        run: make test
